services:
  postgres:
    container_name: weather-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - weather_pg_data:/var/lib/postgresql/data

volumes:
  weather_pg_data: